### ISSUE TITLE
how can i got superpoint.pt files?

### ISSUE THREAD

**Issue by jcyhcs** [Kolkir/superpoint#1]
hi,professor:
thanks for your code! in the examples, requires superpoint.pt file, where can i find it? 
PLEASE!

**Comment by Kolkir** [comment]
Hello, 
If you are talking about the `main.cc` file, then it's assumed that you've exported `superpoint.pt` from the Python program as a PyTorch jit script. You can see how it can be done in the  [`inferencewrapper.py`](https://github.com/Kolkir/superpoint/blob/318c38caa7f1086d60452c738fb035ddafdb3317/python/inferencewrapper.py#L108).
