### ISSUE TITLE
is there any possible realize superpoint algorithm without pytorch or libtorch?

### ISSUE THREAD

**Issue by jcyhcs** [Kolkir/superpoint#2]
hi,professor:
when run superpoint algorithm on jetson embedded platform, use pytorch or libtorch is so heavy, they rely on so huge thrid-party libraries, can you realize this algorithm use native cuda and tensorRT ? that will be greatfull!
PLEASE HELP!

**Comment by Kolkir** [comment]
I'm working now on researching and developing  a lighter version of network that is based on the SuperPoint approach, to make it suitable for embedded devices. The development is going in the [axial-attention-backbone](https://github.com/Kolkir/superpoint/tree/axial-attention-backbone). Hope to finish soon.
