### ISSUE TITLE
got error when run python/main.py

### ISSUE THREAD

**Issue by jcyhcs** [Kolkir/superpoint#3]
hi,professor:
i run python/main.py with command: python3 main.py, then got error:
how can i modify it?
anthor error:
 subparsers = parser.add_subparsers(dest='run_mode', required=True)
  File "main.py", line 26, in main
    subparsers = parser.add_subparsers(dest='run_mode', required=True)
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

please!

**Comment by Kolkir** [comment]
The main branch was outdated, I renamed it. Please consider new implementation.
